server:
  port: 9998
  connection-timeout: 60s
  tomcat:
    max-threads: 500

spring:
  profiles:
    active: h2
  thymeleaf:
    cache: false
  mvc:
    servlet:
      load-on-startup: 1
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true